apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kidp2h/gitops-kafka.git' # Repository GitOps chứa file deployment
    targetRevision: HEAD
    path: k8s/auth-service                                # Thư mục chứa file auth-service.yaml trong repo GitOps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
