apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kidp2h/gitops-kafka.git' # Repository GitOps của bạn
    targetRevision: HEAD
    path: argocd-apps                                     # Thư mục chứa các file YAML của các child app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
